name: Build/Release

on:
  push:
    tags:
      - 'v*'


jobs:
  release:
    runs-on: windows-2019

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10
      #- run: yarn install
      #- run: yarn deploy
      #  env:
      #    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Build/release Electron app
      #  uses: samuelmeuli/action-electron-builder@v1
      #  with: 
      #    github_token: ${{ secrets.github_token }}
        
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}